image: php:8.4-cli

stages:
  - test
  - deploy

services:
  - mysql:8

variables:
  MYSQL_DATABASE: inventory_monitoring
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_DATABASE: inventory_monitoring
  DB_USERNAME: phpmyadmin
  DB_PASSWORD: Reip@Admin123!

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  - apt-get update -yqq
  - apt-get install -y git unzip curl libzip-dev zip libpng-dev openssh-client
  - docker-php-ext-install pdo_mysql zip

  # Install Composer
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer

  # Install dependency
  - composer install --no-interaction --prefer-dist --optimize-autoloader

  # Setup env
  - cp .env.example .env || true
  - php artisan key:generate
  - php artisan jwt:secret --force

  # Wait DB
  - sleep 10

  # Migrate
  - php artisan migrate --force

test:
  stage: test
  script:
    - php artisan test

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVER_IP "
        cd /var/www/inventory_monitoring &&
        git pull origin main &&
        composer install --no-dev --optimize-autoloader &&
        php artisan migrate --force &&
        php artisan config:cache &&
        php artisan route:cache &&
        sudo systemctl restart php8.3-fpm &&
        sudo systemctl restart nginx
      "
  only:
    - main